steps:
# Step 1
- name: 'gcr.io/cloud-builders/docker' 
  entrypoint: 'bash'
  args: [
   '-c', 
   'docker pull gcr.io/$PROJECT_ID/ecom-ms-products:$COMMIT_SHA || exit 0'
  ]

images: [
   'gcr.io/$PROJECT_ID/ecom-ms-products:$COMMIT_SHA'
  ]