steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ecom-ms-products', '.']

# Step 2
- name: 'gcr.io/cloud-builders/kubectl'
  # apply -f k8s/
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gke-ms-app'
# Step 3
- name: 'gcr.io/cloud-builders/kubectl'
  #kubectl set image deployment ecom-ms-products ecom-ms-products=gcr.io/$PROJECT_ID/ecom-ms-products
  args: [
   'set', 
   'image', 
   'deployment', 
   'ecom-ms-products', 
   'ecom-ms-products=gcr.io/$PROJECT_ID/ecom-ms-products'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gke-ms-app'
  # Push the image to Google Container Registry with the latest tag

images: [
   'gcr.io/$PROJECT_ID/ecom-ms-products'
  ]