steps:
- name: 'gcr.io/cloud-builders/docker' # Construye la imagen y la guarda en gcr
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ecom-ms-products', '.']
- name: 'gcr.io/cloud-builders/docker' # Jalamos la imagen del registro de contenedores de google
  entrypoint: 'bash'
  args: ['-c', 'docker pull gcr.io/$PROJECT_ID/ecom-ms-products || exit 0'
  ]
- name: 'gcr.io/cloud-builders/kubectl' # Aplicamos service y deployment yaml de la carpeta k8s
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gke-ms-app'
- name: 'gcr.io/cloud-builders/kubectl' # Desplegamos imagen
  args: [
   'set', 
   'image', 
   'deployment', 
   'ecom-ms-products', 
   'ecom-ms-products=gcr.io/$PROJECT_ID/ecom-ms-products'
  ]
  env: # Push the image to Google Container Registry with the latest tag
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gke-ms-app'
images: [
   'gcr.io/$PROJECT_ID/ecom-ms-products'
  ]