kind: Service
apiVersion: v1
metadata:
  name: ecom-ms-products
spec:
  selector:
     run: ecom-ms-products
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 3602
    nodePort: 30475
  type: LoadBalancer